
2021-03-21 17:25:32.805057 :  Searching vocabulary <<the rates>> at 137 - read_vocabulary_to_search - /Users/truongthuan/Develop/python/blog/dictionary/search.py
2021-03-21 17:25:44.865195 :  saved file the-rates+noun+us.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:25:48.313776 :  error: HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /media/english/us_pron/r/rat/rates/rates_1_us_1.mp3 (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(54, 'Connection reset by peer'))) at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:25:50.552688 :  saved file the-rates+noun+uk.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:25:50.579330 :  Saved <the-rates> successfully. at 37 - searchVocabulary - /Users/truongthuan/Develop/python/blog/dictionary/search.py
2021-03-21 17:25:52.232009 :  error: HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /media/english/us_pron/r/rat/rathe/rather__us_1.mp3 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden'))) at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:25:52.410917 :  error: HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /media/english/us_pron/r/rat/rathe/rather__us_1.mp3 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden'))) at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:25:52.586691 :  error: HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /media/english/us_pron/r/rat/rathe/rather__us_1.mp3 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden'))) at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:25:52.764451 :  error: HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /media/english/us_pron/r/rat/rathe/rather__us_1.mp3 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden'))) at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:25:52.947956 :  error: HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /media/english/us_pron/r/rat/rathe/rather__us_1.mp3 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden'))) at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:26:09.968260 :  error: HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /media/english/us_pron/r/rat/rathe/rather__us_1.mp3 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x110518d90>, 'Connection to 187.243.250.10 timed out. (connect timeout=17)')) at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:26:26.979854 :  error: HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /media/english/us_pron/r/rat/rathe/rather__us_1.mp3 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x110524400>, 'Connection to 208.80.28.208 timed out. (connect timeout=17)')) at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:26:45.348296 :  saved file rather+adverb+us.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:27:05.722493 :  error: HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /media/english/us_pron/r/rat/rathe/rather__us_1.mp3 (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out'))) at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:27:13.809125 :  error: HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /media/english/us_pron/r/rat/rathe/rather__us_1.mp3 (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(54, 'Connection reset by peer'))) at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:27:14.116700 :  error: HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /media/english/us_pron/r/rat/rathe/rather__us_1.mp3 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x110705310>: Failed to establish a new connection: [Errno 61] Connection refused'))) at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:27:14.423589 :  error: HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /media/english/us_pron/r/rat/rathe/rather__us_1.mp3 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x110524eb0>: Failed to establish a new connection: [Errno 61] Connection refused'))) at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:27:14.728749 :  error: HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /media/english/us_pron/r/rat/rathe/rather__us_1.mp3 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x110705a60>: Failed to establish a new connection: [Errno 61] Connection refused'))) at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:27:23.523183 :  saved file rather+adverb+uk.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:27:23.525946 :  save vocabulary <<rather>> type:<<adverb>> successfully at 250 - get_nearby_word_links - /Users/truongthuan/Develop/python/blog/dictionary/searchbase.py
2021-03-21 17:31:53.048157 :  Searching vocabulary <<guessing game>> at 137 - read_vocabulary_to_search - /Users/truongthuan/Develop/python/blog/dictionary/search.py
2021-03-21 17:32:07.597900 :  saved file guessing-game+noun+us.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:32:11.691942 :  saved file guessing-game+noun+uk.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:32:22.656781 :  saved file guessing-game+noun+us.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:32:24.736828 :  saved file guessing-game+noun+uk.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:32:35.143268 :  saved file guessing-game+noun+us.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:32:41.289764 :  saved file guessing-game+noun+uk.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:32:46.308192 :  saved file guessing-game+noun+us.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:32:51.017045 :  saved file guessing-game+noun+uk.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:33:02.557845 :  Searching vocabulary <<guessing game>> at 137 - read_vocabulary_to_search - /Users/truongthuan/Develop/python/blog/dictionary/search.py
2021-03-21 17:33:13.652287 :  saved file guessing-game+noun+us.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:33:15.901126 :  saved file guessing-game+noun+uk.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:33:37.509051 :  saved file guessing-game+noun+us.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:34:50.477517 :  Searching vocabulary <<guessing game>> at 139 - read_vocabulary_to_search - /Users/truongthuan/Develop/python/blog/dictionary/search.py
2021-03-21 17:35:05.116576 :  saved file guessing-game+noun+us.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:35:09.565979 :  saved file guessing-game+noun+uk.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:35:09.600839 :  Saved <guessing-game> successfully. at 37 - searchVocabulary - /Users/truongthuan/Develop/python/blog/dictionary/search.py
2021-03-21 17:35:13.970100 :  saved file guess+verb+us.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:35:16.221400 :  saved file guess+verb+uk.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:35:16.226686 :  save vocabulary <<guess>> type:<<verb>> successfully at 250 - get_nearby_word_links - /Users/truongthuan/Develop/python/blog/dictionary/searchbase.py
2021-03-21 17:39:18.463287 :  Searching vocabulary <<guessing game>> at 139 - read_vocabulary_to_search - /Users/truongthuan/Develop/python/blog/dictionary/search.py
2021-03-21 17:40:05.776711 :  error: HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /media/english/us_pron/g/gue/guess/guessing_game_1_us_1.mp3 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x10e4ab580>, 'Connection to 112.78.186.196 timed out. (connect timeout=17)')) at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:40:11.824704 :  saved file guessing-game+noun+us.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:40:16.917233 :  Searching vocabulary <<guessing game>> at 139 - read_vocabulary_to_search - /Users/truongthuan/Develop/python/blog/dictionary/search.py
2021-03-21 17:44:05.898935 :  Searching vocabulary <<guessing game>> at 139 - read_vocabulary_to_search - /Users/truongthuan/Develop/python/blog/dictionary/search.py
2021-03-21 17:44:35.328568 :  saved file guessing-game+noun+us.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:44:37.890176 :  saved file guessing-game+noun+uk.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:44:47.202822 :  saved file guessing-game+noun+us.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:44:48.323968 :  saved file guessing-game+noun+uk.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:44:53.453938 :  saved file guessing-game+noun+us.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:44:56.021893 :  saved file guessing-game+noun+uk.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:45:07.073787 :  saved file guessing-game+noun+us.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:45:12.403993 :  saved file guessing-game+noun+uk.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:45:15.737699 :  saved file guessing-game+noun+us.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:45:16.792144 :  saved file guessing-game+noun+uk.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:45:25.298691 :  saved file guessing-game+noun+us.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:45:28.781563 :  saved file guessing-game+noun+uk.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:45:33.490136 :  saved file guessing-game+noun+us.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:45:39.326700 :  saved file guessing-game+noun+uk.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:46:54.636272 :  Searching vocabulary <<guessing game>> at 139 - read_vocabulary_to_search - /Users/truongthuan/Develop/python/blog/dictionary/search.py
2021-03-21 17:47:03.499235 :  saved file guessing-game+noun+us.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:47:12.818673 :  saved file guessing-game+noun+uk.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:47:12.836180 :  Saved <guessing-game> successfully. at 37 - searchVocabulary - /Users/truongthuan/Develop/python/blog/dictionary/search.py
2021-03-21 17:47:30.211734 :  error: HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /media/english/us_pron/g/gue/guess/guess__us_1.mp3 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x10df1ef40>, 'Connection to 207.157.220.8 timed out. (connect timeout=17)')) at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:47:47.225400 :  error: HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /media/english/us_pron/g/gue/guess/guess__us_1.mp3 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x10df29730>, 'Connection to 207.157.220.8 timed out. (connect timeout=17)')) at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:48:04.242864 :  error: HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /media/english/us_pron/g/gue/guess/guess__us_1.mp3 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x10df29ee0>, 'Connection to 207.157.220.8 timed out. (connect timeout=17)')) at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:48:21.252158 :  error: HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /media/english/us_pron/g/gue/guess/guess__us_1.mp3 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x10df29c10>, 'Connection to 207.157.220.8 timed out. (connect timeout=17)')) at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:48:38.274526 :  error: HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /media/english/us_pron/g/gue/guess/guess__us_1.mp3 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x10df29130>, 'Connection to 207.157.220.8 timed out. (connect timeout=17)')) at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:48:55.285994 :  error: HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /media/english/us_pron/g/gue/guess/guess__us_1.mp3 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x10ddef6d0>, 'Connection to 208.80.28.208 timed out. (connect timeout=17)')) at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:49:04.537719 :  error: HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /media/english/us_pron/g/gue/guess/guess__us_1.mp3 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123)'))) at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:49:07.263948 :  saved file guess+verb+us.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:49:24.475806 :  Searching vocabulary <<guessing game>> at 136 - read_vocabulary_to_search - /Users/truongthuan/Develop/python/blog/dictionary/search.py
2021-03-21 17:50:11.016798 :  error: HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /media/english/us_pron/g/gue/guess/guessing_game_1_us_1.mp3 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1045a29a0>, 'Connection to 23.95.238.164 timed out. (connect timeout=17)')) at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:50:14.221388 :  saved file guessing-game+noun+us.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:50:38.489308 :  saved file guessing-game+noun+uk.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:50:38.503578 :  Saved <guessing-game> successfully. at 37 - searchVocabulary - /Users/truongthuan/Develop/python/blog/dictionary/search.py
2021-03-21 17:50:50.261566 :  error: HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /media/english/us_pron/g/gue/guess/guess__us_1.mp3 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1046fbc40>: Failed to establish a new connection: [Errno 61] Connection refused'))) at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:50:50.570201 :  error: HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /media/english/us_pron/g/gue/guess/guess__us_1.mp3 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x104704430>: Failed to establish a new connection: [Errno 61] Connection refused'))) at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:50:50.877574 :  error: HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /media/english/us_pron/g/gue/guess/guess__us_1.mp3 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x104704be0>: Failed to establish a new connection: [Errno 61] Connection refused'))) at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:50:51.183922 :  error: HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /media/english/us_pron/g/gue/guess/guess__us_1.mp3 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10470b3d0>: Failed to establish a new connection: [Errno 61] Connection refused'))) at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:50:51.446495 :  error: HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /media/english/us_pron/g/gue/guess/guess__us_1.mp3 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10470bb80>: Failed to establish a new connection: [Errno 61] Connection refused'))) at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:50:51.714171 :  error: HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /media/english/us_pron/g/gue/guess/guess__us_1.mp3 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x104719370>: Failed to establish a new connection: [Errno 61] Connection refused'))) at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:51:08.721296 :  error: HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /media/english/us_pron/g/gue/guess/guess__us_1.mp3 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x10470b1c0>, 'Connection to 159.65.69.186 timed out. (connect timeout=17)')) at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:51:09.299685 :  error: HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /media/english/us_pron/g/gue/guess/guess__us_1.mp3 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden'))) at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:51:09.609847 :  error: HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /media/english/us_pron/g/gue/guess/guess__us_1.mp3 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden'))) at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:51:09.939128 :  error: HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /media/english/us_pron/g/gue/guess/guess__us_1.mp3 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden'))) at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:51:10.295494 :  error: HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /media/english/us_pron/g/gue/guess/guess__us_1.mp3 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden'))) at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:51:10.606575 :  error: HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /media/english/us_pron/g/gue/guess/guess__us_1.mp3 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden'))) at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:51:10.963046 :  error: HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /media/english/us_pron/g/gue/guess/guess__us_1.mp3 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden'))) at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:51:22.213388 :  Searching vocabulary <<guessing game>> at 136 - read_vocabulary_to_search - /Users/truongthuan/Develop/python/blog/dictionary/search.py
2021-03-21 17:51:36.679831 :  Searching vocabulary <<guessing game>> at 136 - read_vocabulary_to_search - /Users/truongthuan/Develop/python/blog/dictionary/search.py
2021-03-21 17:51:48.634782 :  saved file guessing-game+noun+us.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:51:50.859946 :  saved file guessing-game+noun+uk.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:52:02.085269 :  Searching vocabulary <<guessing game>> at 136 - read_vocabulary_to_search - /Users/truongthuan/Develop/python/blog/dictionary/search.py
2021-03-21 17:52:09.626988 :  saved file guessing-game+noun+us.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:52:11.641661 :  saved file guessing-game+noun+uk.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:52:31.117818 :  Searching vocabulary <<guessing game>> at 136 - read_vocabulary_to_search - /Users/truongthuan/Develop/python/blog/dictionary/search.py
2021-03-21 17:52:52.595383 :  Searching vocabulary <<guessing game>> at 136 - read_vocabulary_to_search - /Users/truongthuan/Develop/python/blog/dictionary/search.py
2021-03-21 17:53:00.111473 :  saved file guessing-game+noun+us.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:53:04.721337 :  saved file guessing-game+noun+uk.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:55:57.759718 :  Searching vocabulary <<guessing game>> at 136 - read_vocabulary_to_search - /Users/truongthuan/Develop/python/blog/dictionary/search.py
2021-03-21 17:56:20.093281 :  saved file guessing-game+noun+us.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:56:22.347472 :  saved file guessing-game+noun+uk.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:56:30.334156 :  saved file guessing-game+noun+us.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:56:33.302796 :  saved file guessing-game+noun+uk.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:56:56.527246 :  error: HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /media/english/us_pron/g/gue/guess/guessing_game_1_us_1.mp3 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x106f7c760>, 'Connection to 118.27.27.165 timed out. (connect timeout=17)')) at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:57:05.727960 :  saved file guessing-game+noun+us.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:57:16.815300 :  saved file guessing-game+noun+uk.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:58:08.433385 :  Searching vocabulary <<guessing game>> at 136 - read_vocabulary_to_search - /Users/truongthuan/Develop/python/blog/dictionary/search.py
2021-03-21 17:58:36.285010 :  saved file guessing-game+noun+us.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:58:44.996608 :  saved file guessing-game+noun+uk.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:58:45.012318 :  Saved <Name: guessing-game> successfully. at 37 - searchVocabulary - /Users/truongthuan/Develop/python/blog/dictionary/search.py
2021-03-21 17:58:45.703570 :  error: HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /media/english/us_pron/g/gue/guess/guess__us_1.mp3 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1079d3940>: Failed to establish a new connection: [Errno 61] Connection refused'))) at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:58:46.011259 :  error: HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /media/english/us_pron/g/gue/guess/guess__us_1.mp3 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1079df130>: Failed to establish a new connection: [Errno 61] Connection refused'))) at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:58:46.318626 :  error: HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /media/english/us_pron/g/gue/guess/guess__us_1.mp3 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1079df8e0>: Failed to establish a new connection: [Errno 61] Connection refused'))) at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:58:46.625786 :  error: HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /media/english/us_pron/g/gue/guess/guess__us_1.mp3 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1078a58e0>: Failed to establish a new connection: [Errno 61] Connection refused'))) at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:58:46.931747 :  error: HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /media/english/us_pron/g/gue/guess/guess__us_1.mp3 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1079df8b0>: Failed to establish a new connection: [Errno 61] Connection refused'))) at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:59:03.942411 :  error: HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /media/english/us_pron/g/gue/guess/guess__us_1.mp3 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1079e90d0>, 'Connection to 37.120.192.154 timed out. (connect timeout=17)')) at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:59:13.154001 :  saved file guess+verb+us.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:59:27.590766 :  saved file guess+verb+uk.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 17:59:27.594611 :  save vocabulary <<guess>> type:<<verb>> successfully at 250 - get_nearby_word_links - /Users/truongthuan/Develop/python/blog/dictionary/searchbase.py
2021-03-21 18:02:09.322826 :  Searching vocabulary <<guessing game>> at 136 - read_vocabulary_to_search - /Users/truongthuan/Develop/python/blog/dictionary/search.py
2021-03-21 18:03:28.537179 :  saved file guessing-game+noun+us.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 18:03:45.581336 :  saved file guessing-game+noun+uk.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 18:03:45.596672 :  Saved <Name: guessing-game> successfully. at 37 - searchVocabulary - /Users/truongthuan/Develop/python/blog/dictionary/search.py
2021-03-21 18:04:00.900710 :  saved file guess+verb+us.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 18:04:01.800200 :  saved file guess+verb+uk.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 18:04:01.812071 :  save vocabulary <<guess>> type:<<verb>> successfully at 250 - get_nearby_word_links - /Users/truongthuan/Develop/python/blog/dictionary/searchbase.py
2021-03-21 18:04:49.723746 :  Searching vocabulary <<the rates>> at 136 - read_vocabulary_to_search - /Users/truongthuan/Develop/python/blog/dictionary/search.py
2021-03-21 18:05:33.774438 :  saved file the-rates+noun+us.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 23:33:06.201859 :  saved file than+preposition, conjunction+us.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 23:33:08.677149 :  saved file than+preposition, conjunction+uk.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 23:33:25.778970 :  saved file than+preposition, conjunction+us.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 23:33:25.975974 :  error: HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /media/english/us_pron/t/tha/than_/than__us_3_rr.mp3 (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(54, 'Connection reset by peer'))) at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 23:33:26.977937 :  saved file than+preposition, conjunction+uk.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 23:33:44.281813 :  saved file than+preposition, conjunction+us.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
2021-03-21 23:33:48.180063 :  saved file than+preposition, conjunction+uk.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
 2021-03-21 23:50:38.448561 : error: HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /media/english/us_pron/t/tha/than_/than__us_3_rr.mp3 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Too many open connections'))) at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
 2021-03-21 23:50:39.085918 : error: HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /media/english/us_pron/t/tha/than_/than__us_3_rr.mp3 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Too many open connections'))) at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
 2021-03-21 23:50:39.709031 : error: HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /media/english/us_pron/t/tha/than_/than__us_3_rr.mp3 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Too many open connections'))) at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
 2021-03-21 23:50:40.429685 : error: HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /media/english/us_pron/t/tha/than_/than__us_3_rr.mp3 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Too many open connections'))) at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
 2021-03-21 23:50:41.149094 : error: HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /media/english/us_pron/t/tha/than_/than__us_3_rr.mp3 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Too many open connections'))) at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
 2021-03-21 23:50:49.756664 : saved file than+preposition, conjunction+us.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
 2021-03-21 23:50:51.479799 : error: HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /media/english/us_pron/t/tha/than_/than__us_3_rr.mp3 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Too many open connections'))) at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
 2021-03-21 23:50:52.125858 : error: HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /media/english/us_pron/t/tha/than_/than__us_3_rr.mp3 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Too many open connections'))) at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
 2021-03-21 23:50:53.014772 : error: HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /media/english/us_pron/t/tha/than_/than__us_3_rr.mp3 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Too many open connections'))) at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
 2021-03-21 23:50:53.945618 : error: HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /media/english/us_pron/t/tha/than_/than__us_3_rr.mp3 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Too many open connections'))) at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
 2021-03-21 23:50:54.548318 : error: HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /media/english/us_pron/t/tha/than_/than__us_3_rr.mp3 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Too many open connections'))) at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
 2021-03-21 23:50:55.378563 : error: HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /media/english/us_pron/t/tha/than_/than__us_3_rr.mp3 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Too many open connections'))) at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
 2021-03-21 23:51:12.387930 : error: HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /media/english/us_pron/t/tha/than_/than__us_3_rr.mp3 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1051c3460>, 'Connection to 207.157.220.8 timed out. (connect timeout=17)')) at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
 2021-03-21 23:51:22.984427 : saved file than+preposition, conjunction+uk.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
 2021-03-21 23:51:22.999630 : value too long for type character varying(20)
 at 104 - check_search - /Users/truongthuan/Develop/python/blog/dictionary/search.py
 2021-03-21 23:51:24.147139 : HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /definition/english/than (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 500 Internal Server Error'))) at 104 - check_search - /Users/truongthuan/Develop/python/blog/dictionary/search.py
 2021-03-21 23:51:31.262785 : HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /definition/english/than (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out'))) at 104 - check_search - /Users/truongthuan/Develop/python/blog/dictionary/search.py
 2021-03-21 23:51:31.721757 : HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /definition/english/than (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Too many open connections'))) at 104 - check_search - /Users/truongthuan/Develop/python/blog/dictionary/search.py
 2021-03-21 23:51:32.654108 : HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /definition/english/than (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden'))) at 104 - check_search - /Users/truongthuan/Develop/python/blog/dictionary/search.py
 2021-03-21 23:51:41.145964 : saved file than+preposition, conjunction+us.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
 2021-03-21 23:51:45.104536 : saved file than+preposition, conjunction+uk.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
 2021-03-21 23:51:45.109109 : value too long for type character varying(20)
 at 104 - check_search - /Users/truongthuan/Develop/python/blog/dictionary/search.py
 2021-03-21 23:51:50.773528 : saved file than+preposition, conjunction+us.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
 2021-03-21 23:51:54.348538 : saved file than+preposition, conjunction+uk.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
 2021-03-21 23:51:54.370381 : value too long for type character varying(20)
 at 104 - check_search - /Users/truongthuan/Develop/python/blog/dictionary/search.py
 2021-03-21 23:52:01.386461 : HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /definition/english/than (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x10521f8e0>, 'Connection to 208.80.28.208 timed out. (connect timeout=7)')) at 104 - check_search - /Users/truongthuan/Develop/python/blog/dictionary/search.py
 2021-03-21 23:52:08.397529 : HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /definition/english/than (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1052df2e0>, 'Connection to 213.105.29.14 timed out. (connect timeout=7)')) at 104 - check_search - /Users/truongthuan/Develop/python/blog/dictionary/search.py
 2021-03-21 23:52:32.657468 : saved file than+preposition, conjunction+us.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
 2021-03-21 23:52:44.147878 : saved file than+preposition, conjunction+uk.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
 2021-03-21 23:52:44.149984 : value too long for type character varying(20)
 at 104 - check_search - /Users/truongthuan/Develop/python/blog/dictionary/search.py
 2021-03-21 23:53:34.926517 : saved file than+preposition, conjunction+us.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
 2021-03-21 23:53:39.930699 : saved file than+preposition, conjunction+uk.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
 2021-03-21 23:53:39.946285 : Saved <Name: than> successfully. at 37 - searchVocabulary - /Users/truongthuan/Develop/python/blog/dictionary/search.py
 2021-03-21 23:53:40.207913 : save vocabulary <<the Thames>> type:<<None>> successfully at 250 - get_nearby_word_links - /Users/truongthuan/Develop/python/blog/dictionary/searchbase.py
 2021-03-21 23:53:40.468395 : save vocabulary <<the Thames Barrier>> type:<<None>> successfully at 250 - get_nearby_word_links - /Users/truongthuan/Develop/python/blog/dictionary/searchbase.py
 2021-03-21 23:53:58.457236 : error: HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /media/english/us_pron/t/tha/thana/thana__us_1.mp3 (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(54, 'Connection reset by peer'))) at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
 2021-03-21 23:54:17.957112 : saved file thana+noun+us.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
 2021-03-21 23:54:21.805181 : error: HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /media/english/us_pron/t/tha/thana/thana__us_1.mp3 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Too many open connections'))) at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
 2021-03-21 23:54:38.811691 : error: HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /media/english/us_pron/t/tha/thana/thana__us_1.mp3 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1035fcdf0>, 'Connection to 165.22.243.240 timed out. (connect timeout=17)')) at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
 2021-03-21 23:54:47.062362 : saved file thana+noun+uk.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
 2021-03-21 23:54:47.064940 : save vocabulary <<thana>> type:<<noun>> successfully at 250 - get_nearby_word_links - /Users/truongthuan/Develop/python/blog/dictionary/searchbase.py
 2021-03-21 23:55:04.296274 : error: HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /media/english/us_pron/t/tha/thang/thang__us_1.mp3 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x10356cf10>, 'Connection to 196.216.215.117 timed out. (connect timeout=17)')) at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
 2021-03-21 23:55:21.414265 : error: HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /media/english/us_pron/t/tha/thang/thang__us_1.mp3 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x103616700>, 'Connection to 196.216.215.117 timed out. (connect timeout=17)')) at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
 2021-03-21 23:55:38.913794 : error: HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /media/english/us_pron/t/tha/thang/thang__us_1.mp3 (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(54, 'Connection reset by peer'))) at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
 2021-03-21 23:55:55.924673 : error: HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /media/english/us_pron/t/tha/thang/thang__us_1.mp3 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x103616fa0>, 'Connection to 196.216.215.117 timed out. (connect timeout=17)')) at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
 2021-03-21 23:56:13.008516 : error: HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /media/english/us_pron/t/tha/thang/thang__us_1.mp3 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1035956a0>, 'Connection to 196.216.215.117 timed out. (connect timeout=17)')) at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
 2021-03-21 23:56:17.355170 : saved file thang+noun+us.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
 2021-03-21 23:56:34.365921 : error: HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /media/english/us_pron/t/tha/thang/thang__us_1.mp3 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x103577760>, 'Connection to 157.230.103.189 timed out. (connect timeout=17)')) at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
 2021-03-21 23:56:51.377469 : error: HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /media/english/us_pron/t/tha/thang/thang__us_1.mp3 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x103595940>, 'Connection to 157.230.103.189 timed out. (connect timeout=17)')) at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
 2021-03-21 23:57:08.394869 : error: HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /media/english/us_pron/t/tha/thang/thang__us_1.mp3 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x103595190>, 'Connection to 157.230.103.189 timed out. (connect timeout=17)')) at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
 2021-03-21 23:57:25.405692 : error: HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /media/english/us_pron/t/tha/thang/thang__us_1.mp3 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1036132e0>, 'Connection to 157.230.103.189 timed out. (connect timeout=17)')) at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
 2021-03-21 23:57:42.532828 : error: HTTPSConnectionPool(host='www.oxfordlearnersdictionaries.com', port=443): Max retries exceeded with url: /media/english/us_pron/t/tha/thang/thang__us_1.mp3 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x103577340>, 'Connection to 157.230.103.189 timed out. (connect timeout=17)')) at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
 2021-03-21 23:57:51.976042 : saved file thang+noun+uk.mp3 at 56 - downloadFileFromUrl - /Users/truongthuan/Develop/python/blog/dictionary/helper.py
 2021-03-21 23:57:51.978577 : save vocabulary <<thang>> type:<<noun>> successfully at 250 - get_nearby_word_links - /Users/truongthuan/Develop/python/blog/dictionary/searchbase.py